### ISSUE TITLE
generating Sphinx docs + Jupyter Book

### ISSUE THREAD

**Issue by asemposki** [bandframework/Taweret#100]
Building both a Sphinx docs page and a Jupyter Book from the same GitHub repo is not allowed with GitHub Actions since one repo can only possess one domain. Jared looked at a few options for a workaround that won't be too cumbersome to implement and/or maintain, and one of the better ones is to build the Sphinx docs through Read The Docs, so that we can build the Jupyter Book from the repo. This seems to be relatively straightforward once you get through allowing Read the Docs all of the permissions it will need. Then the Book can be deployed using Actions, and we can point to the Book domain in our documentation for the interested user. The Book would then also not be on a separate, stripped branch, as it is now. I will start working on a branch that does this Jupyter Book building, and Jared will work on the Sphinx Docs through Read the Docs. 

The toy repo that Jared set up to test these ideas is below, which we can implement here. 
https://github.com/jared321/MyJBook/tree/main

**Comment by jared321** [comment]
In `91_SphinxClean`, the sphinx docs builds have one critical (actually unimportant) failure for a Trees notebook and smart quote warnings related to several notebooks.  As a result, the sphinx/readthedocs GH actions are currently configured to treat warnings as warnings rather than errors.  Based on my experience, this is not good because errors are printed to stdout, but the doc generation exit code is still zero, which implies that GH actions will not register the error.  Therefore, this action should only be run with warnings treated as errors.  I will leave that as is in PR #99.

Alexandra has agreed that after she moves the notebooks out of sphinx and to the Jupyterbook as described in this issue, we can
* confirm that sphinx builds correctly with no warnings or errors,
* adjust the GH action and RTD configs so that all sphinx warnings are treated as errors, and
* check for these same issues when notebooks are incorporated in the jupyterbook.

**Comment by asemposki** [comment]
Once we merge PR #112 in, I will close this issue as completed.
