### ISSUE TITLE
JOSS Paper review - code comments

### ISSUE THREAD

**Issue by julienmalard** [bandframework/Taweret#56]
My main concern is the ease of installation of the software. I strongly recommend distributing it on PyPI and using PDM (or similar) and a pyproject.toml to manage dependences, rather than a setup.py and requirements.txt. This is important to ensure sustainable dependency management into the future.

Other non-python dependencies that are currently described in the installation section of the online documentation would be better if automatically installable though a Python function included with the package.

**Comment by ominusliticus** [comment]
Is there a reason to use the OO framework over what we have now? We have not considered any code coverage, but will now look into it, thank you for the suggestion.

**Comment by julienmalard** [comment]
The main advantages of the OO framework are that (1) test runs are named in the test output, and (2) all tests run and errors are only reported at the end, so any errors along the way are clearly documented and don't stop other tests from running.
For example, see passing tests here: https://github.com/julienmalard/traDSSAT/actions/runs/8135344210/job/22229734167
Since they pass, there isn't that much output, but if any failed the output would be much more detailed. In addition, many IDEs such as PyCharm format the test output by subtest in the test runner console if they're written as OO tests.

**Comment by ominusliticus** [comment]
So I looked into the pytesting framework, particular for OO, and here they advocate for it as a way of incrementally (i.e., only continuing to test if previous steps succeeded) testing your package, otherwise all the examples they give are primarily function based. At least in terms of success reporting, our reports look the same (comparing the workflow you sent us, with what we currently have). From the pytest documentation, I do see the difference you mention about each test being named.

Our question: Is the suggestion of moving towards an OO framework a blocking suggestion?
We will definitely add CodeCov (still need to look into this).

**Comment by julienmalard** [comment]
A minor point on code coverage - it seems to be currently set up to measure the coverage of the test files, and not of the package files themselves (which may explain the near-100% coverage).

**Comment by ominusliticus** [comment]
I tried to google an example of code coverage testing a full repository, but haven't been able to. Could you point me to an example so that I may understand?

**Comment by julienmalard** [comment]
Hello,
Here's an example: https://github.com/reseau-constellation/client-python

As can be seen [here](https://app.codecov.io/github/reseau-constellation/client-python), the source files are also included in the coverage report.

**Comment by ominusliticus** [comment]
@julienmalard 
Sorry for the delay, we have implemented the code coverage for the whole package

**Comment by ominusliticus** [comment]
@julienmalard  is it okay to close this issue?

**Comment by julienmalard** [comment]
Yes, looks good!
